#
# vcpkg.mk - make variables and rules specific to
#                     Visual Studio 16 / 2019
#

WindowsNT = 1
x86Processor = 1

BINDIR = bin
LIBDIR = lib

ABSTOP = $(shell cd $(TOP); pwd)

PYTHON = python

# Windows builds require a shared library build
BuildSharedLibrary = 1
# This will be replaced
BuildDebugBinary = 1

# Use the following set of flags to build and use multithreaded DLLs
#
MSVC_DLL_CXXNODEBUGFLAGS       = @VCPKG_DETECTED_CMAKE_CXX_FLAGS_RELEASE@
MSVC_DLL_CXXLINKNODEBUGOPTIONS = @VCPKG_DETECTED_CMAKE_SHARED_LINKER_FLAGS_RELEASE@
MSVC_DLL_CNODEBUGFLAGS         = @VCPKG_DETECTED_CMAKE_C_FLAGS_RELEASE@
MSVC_DLL_CLINKNODEBUGOPTIONS   = @VCPKG_DETECTED_CMAKE_SHARED_LINKER_FLAGS_RELEASE@
#
MSVC_DLL_CXXDEBUGFLAGS         = @VCPKG_DETECTED_CMAKE_CXX_FLAGS_DEBUG@
MSVC_DLL_CXXLINKDEBUGOPTIONS   = @VCPKG_DETECTED_CMAKE_SHARED_LINKER_FLAGS_DEBUG@
MSVC_DLL_CDEBUGFLAGS           = @VCPKG_DETECTED_CMAKE_C_FLAGS_DEBUG@
MSVC_DLL_CLINKDEBUGOPTIONS     = @VCPKG_DETECTED_CMAKE_SHARED_LINKER_FLAGS_DEBUG@
#
# Or
#
# Use the following set of flags to build and use multithread static libraries
#
MSVC_STATICLIB_CXXNODEBUGFLAGS       = @VCPKG_DETECTED_CMAKE_CXX_FLAGS_RELEASE@ -MT
MSVC_STATICLIB_CXXLINKNODEBUGOPTIONS = @VCPKG_DETECTED_CMAKE_STATIC_LINKER_FLAGS_RELEASE@
MSVC_STATICLIB_CNODEBUGFLAGS         = @VCPKG_DETECTED_CMAKE_CXX_FLAGS_RELEASE@ -MT
MSVC_STATICLIB_CLINKNODEBUGOPTIONS   = @VCPKG_DETECTED_CMAKE_STATIC_LINKER_FLAGS_RELEASE@

MSVC_STATICLIB_CXXDEBUGFLAGS         = @VCPKG_DETECTED_CMAKE_CXX_FLAGS_DEBUG@ -MTd
MSVC_STATICLIB_CXXLINKDEBUGOPTIONS   = @VCPKG_DETECTED_CMAKE_STATIC_LINKER_FLAGS_DEBUG@
MSVC_STATICLIB_CDEBUGFLAGS           = @VCPKG_DETECTED_CMAKE_C_FLAGS_DEBUG@ -MTd
MSVC_STATICLIB_CLINKDEBUGOPTIONS     = @VCPKG_DETECTED_CMAKE_STATIC_LINKER_FLAGS_DEBUG@

#
# Include general win32 things
#

include $(THIS_IMPORT_TREE)/mk/win32.mk

MANIFESTTOOL = @VCPKG_DETECTED_CMAKE_MT@
RCTOOL       = @VCPKG_DETECTED_CMAKE_RC_COMPILER@
